#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Unified persistence script for w11-theming-suite transparency effects.
.DESCRIPTION
    Background script that maintains all transparency effects across process
    restarts and login sessions. Handles:
    - Taskbar transparency (SWCA or TAP injection into explorer.exe)
    - Start Menu transparency (ShellTAP into StartMenuExperienceHost.exe)
    - Action Center transparency (ShellTAP into ShellExperienceHost.exe)
    - App window + context menu backdrops (BackdropWatcher with DWM)
    - Auto re-injection when target processes restart (WMI event watch)

    This script is generated and registered by Register-W11TransparencyPersistence.
    It runs hidden at login via a VBScript wrapper.
.NOTES
    DO NOT EDIT MANUALLY -- regenerated by Register-W11TransparencyPersistence.
#>
param(
    [string]$ConfigPath
)

# --- Load config ---
if (-not $ConfigPath -or -not (Test-Path $ConfigPath)) {
    Write-Error "Config file not found: $ConfigPath"
    exit 1
}

$config = Get-Content $ConfigPath -Raw | ConvertFrom-Json

# --- Import module ---
$modulePath = $config.modulePath
if (-not (Test-Path $modulePath)) {
    Write-Error "Module not found: $modulePath"
    exit 1
}

Import-Module $modulePath -Force -ErrorAction Stop

# --- Helper: Apply all transparency effects ---
function Apply-AllEffects {
    param([object]$cfg)

    # 1. Taskbar (SWCA)
    if ($cfg.taskbar.enabled) {
        try {
            $taskbarParams = @{ Style = $cfg.taskbar.style }
            if ($cfg.taskbar.color) { $taskbarParams.Color = $cfg.taskbar.color }
            if ($cfg.taskbar.allMonitors) { $taskbarParams.AllMonitors = $true }
            Set-W11NativeTaskbarTransparency @taskbarParams
        } catch {
            Write-Warning "Taskbar transparency failed: $_"
        }
    }

    # 2. Taskbar TAP injection (for XAML-level transparency)
    if ($cfg.taskbarTAP.enabled) {
        try {
            Invoke-TaskbarTAPInject -Mode $cfg.taskbarTAP.mode
        } catch {
            Write-Warning "Taskbar TAP injection failed: $_"
        }
    }

    # 3. Start Menu
    if ($cfg.startMenu.enabled) {
        try {
            Invoke-StartMenuTransparency -Mode $cfg.startMenu.mode
        } catch {
            Write-Warning "Start Menu transparency failed: $_"
        }
    }

    # 4. Action Center
    if ($cfg.actionCenter.enabled) {
        try {
            Invoke-ActionCenterTransparency -Mode $cfg.actionCenter.mode
        } catch {
            Write-Warning "Action Center transparency failed: $_"
        }
    }

    # 5. App windows + context menus (BackdropWatcher)
    if ($cfg.appWindows.enabled) {
        try {
            if (-not [W11ThemeSuite.BackdropWatcher]::IsRunning) {
                $watcherParams = @{ Style = $cfg.appWindows.backdrop }
                if ($cfg.appWindows.darkMode) { $watcherParams.DarkMode = $true }
                if ($cfg.contextMenus.enabled) { $watcherParams.IncludeContextMenus = $true }
                Start-W11BackdropWatcher @watcherParams
            }
        } catch {
            Write-Warning "BackdropWatcher failed: $_"
        }
    }
}

# --- Initial delay for shell to fully load ---
Start-Sleep -Seconds 5

# --- Apply all effects initially ---
Write-Host "[Watch-W11Transparency] Applying initial transparency effects..."
Apply-AllEffects -cfg $config

# --- WMI process watch for auto re-injection ---
# Monitor for process creation of target XAML host processes
$targetProcesses = @()
if ($config.startMenu.enabled) { $targetProcesses += 'StartMenuExperienceHost.exe' }
if ($config.actionCenter.enabled) { $targetProcesses += 'ShellExperienceHost.exe' }
if ($config.taskbarTAP.enabled) { $targetProcesses += 'explorer.exe' }

if ($targetProcesses.Count -gt 0) {
    $nameFilter = ($targetProcesses | ForEach-Object { "TargetInstance.Name = '$_'" }) -join ' OR '
    $wmiQuery = "SELECT * FROM __InstanceCreationEvent WITHIN 5 WHERE TargetInstance ISA 'Win32_Process' AND ($nameFilter)"

    Write-Host "[Watch-W11Transparency] Registering WMI process watcher for: $($targetProcesses -join ', ')"

    try {
        Register-WmiEvent -Query $wmiQuery -Action {
            $procName = $Event.SourceEventArgs.NewEvent.TargetInstance.Name
            Write-Host "[Watch-W11Transparency] Process started: $procName -- re-applying effects in 3s..."
            Start-Sleep -Seconds 3

            switch ($procName) {
                'StartMenuExperienceHost.exe' {
                    if ($config.startMenu.enabled) {
                        try { Invoke-StartMenuTransparency -Mode $config.startMenu.mode }
                        catch { Write-Warning "Re-inject Start Menu failed: $_" }
                    }
                }
                'ShellExperienceHost.exe' {
                    if ($config.actionCenter.enabled) {
                        try { Invoke-ActionCenterTransparency -Mode $config.actionCenter.mode }
                        catch { Write-Warning "Re-inject Action Center failed: $_" }
                    }
                }
                'explorer.exe' {
                    Start-Sleep -Seconds 5  # explorer needs more time to initialize
                    if ($config.taskbar.enabled) {
                        try {
                            $taskbarParams = @{ Style = $config.taskbar.style }
                            if ($config.taskbar.color) { $taskbarParams.Color = $config.taskbar.color }
                            if ($config.taskbar.allMonitors) { $taskbarParams.AllMonitors = $true }
                            Set-W11NativeTaskbarTransparency @taskbarParams
                        } catch { Write-Warning "Re-apply taskbar SWCA failed: $_" }
                    }
                    if ($config.taskbarTAP.enabled) {
                        try { Invoke-TaskbarTAPInject -Mode $config.taskbarTAP.mode }
                        catch { Write-Warning "Re-inject taskbar TAP failed: $_" }
                    }
                }
            }
        } -SourceIdentifier 'W11TransparencyProcessWatch'
    } catch {
        Write-Warning "WMI event registration failed: $_"
    }
}

# --- Keep alive ---
Write-Host "[Watch-W11Transparency] Persistence active. Monitoring for process restarts..."
while ($true) {
    Start-Sleep -Seconds 60
}
